### ISSUE TITLE
Consider changing the name?

### ISSUE THREAD

**Issue by jinpark** [camirmas/go-stop-server#51]
Hi there, I found this repo while searching for how to do graphql/absinth/phoenix testing and just wanted to suggest a name change of the repo.

Not sure if you were aware but [Go-Stop](https://en.wikipedia.org/wiki/Go-Stop) is actually a name of a Korean card game. It MIGHT lead to some confusion but it is pretty obvious from the code and comments what game this is. (And Go/Baduk/Weiqi is a much more popular game anyways...)

Just letting you know!

**Comment by camirmas** [comment]
This repo is no longer under development, but thanks for the heads up!
